version: '3.8'

services:
  backend:
    build:
      context: ./back
    container_name: backend-restaurantes
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build:
      context: ./front
    container_name: frontend-restaurantes
    ports:
      - "8080:80"
    restart: always
